spring.application.name=gestion-guias

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:oracle:thin:@//url-de-tu-oracle-cloud:1521/XEPDB1
spring.datasource.username=tu_usuario
spring.datasource.password=tu_password
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://guiasdespachobz.b2clogin.com/07f5915e-0373-4db4-b45c-1837e5e1d9ea/B2C_1_signupsignin/discovery/v2.0/keys