spring.application.name=gestion-guias

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:h2:mem:guiasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://guiasdespachobz.b2clogin.com/07f5915e-0373-4db4-b45c-1837e5e1d9ea/B2C_1_signupsignin/discovery/v2.0/keys